//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookClub.AppData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.OrderToBooks = new HashSet<OrderToBooks>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string BookDescription { get; set; }
        public string BookPhoto { get; set; }
        public decimal BookPrice { get; set; }
        public int BookDiscount { get; set; }
        public int BookCountInStock { get; set; }
        public int BookManufacturerId { get; set; }
        public int BookAuthorId { get; set; }

        public decimal BookTotalPrice { get; set; }

        public int CountBookInOrder { get; set; }

        public virtual Authors Authors { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderToBooks> OrderToBooks { get; set; }
    }
}
